baseURL = 'https://fanhhh.top/'
languageCode = 'zh-cn'
title = "Fanhhh's blog"
theme = 'PaperMod'

sectionPagesMenu = "main"

# --- ä¿®æ”¹è¿™é‡Œï¼šç¡®ä¿ä¸»é¡µç”Ÿæˆ JSON ç´¢å¼• ---
[outputs]
    home = ["HTML", "RSS", "JSON"]

[params]
    description = "Fanhhhçš„æŠ€æœ¯ä¸ç”Ÿæ´»è®°å½•"
    defaultTheme = "auto"
    showCodeCopyButtons = true 
    comments = true 

    [params.twikoo]
        enable = true
        envId = 'https://comment.fanhhh.top' 

    [params.homeInfoParams]
        Title = "Welcomeï¼Œè¿™é‡Œæ˜¯æŸç†å·¥å¤§å­¦çš„å­¦ç”Ÿçš„blog ğŸ‘‹"
        Content = "è¿™é‡Œæä¾›ä¸€äº›å…³äºæŠ€æœ¯çš„è¯é¢˜ï¼Œå´‡å°šè‡ªç”±ï¼Œæ¬¢è¿å¤§å®¶è‡ªç”±ç•™è¨€"

    [[params.socialIcons]]
        name = "github"
        url = "https://github.com/Fax-han"

[menu]
    [[menu.main]]
        identifier = "archives"
        name = "æ–‡ç« åˆ—è¡¨"
        url = "/archives" 
        weight = 20
    
    [[menu.main]]
        identifier = "tags"
        name = "æ ‡ç­¾"
        url = "/tags"
        weight = 30

    [[menu.main]]
        identifier = "search"
        name = "æœç´¢"
        url = "/search"
        weight = 40