baseURL = 'https://Fax-han.github.io/'
languageCode = 'zh-cn'
title = "Fanhhh's blog"
theme = 'PaperMod'

# âš ï¸ å¿…é¡»å¼€å¯è¿™ä¸ªï¼Œæœç´¢åŠŸèƒ½æ‰èƒ½å¥½ç”¨
outputs = ["HTML", "JSON"]

[params]
    description = "Fanhhhçš„æŠ€æœ¯ä¸ç”Ÿæ´»è®°å½•"
    defaultTheme = "auto"
    comments = true # å…¨å±€å¼€å¯è¯„è®º

    # æ··åˆæ¨¡å¼ï¼šä¸Šé¢æ˜¯è‡ªæˆ‘ä»‹ç»ï¼Œä¸‹é¢æ˜¯æ–‡ç« åˆ—è¡¨
    [params.homeInfoParams]
        Title = "Welcomeï¼Œè¿™é‡Œæ˜¯æŸç†å·¥å¤§å­¦çš„å­¦ç”Ÿçš„blog ğŸ‘‹"
        Content = "è¿™é‡Œæä¾›ä¸€äº›å…³äºæŠ€æœ¯çš„è¯é¢˜ï¼Œå´‡å°šè‡ªç”±ï¼Œæ¬¢è¿å¤§å®¶è‡ªç”±ç•™è¨€"

    [[params.socialIcons]]
        name = "github"
        url = "https://github.com/Fax-han"

# èœå•é…ç½®
[menu]
    [[menu.main]]
        identifier = "home"
        name = "é¦–é¡µ"
        url = "/"
        weight = 10
    
    [[menu.main]]
        identifier = "archives"
        name = "æ–‡ç« åˆ—è¡¨"
        url = "/archives/"
        weight = 20
    
    [[menu.main]]
        identifier = "tags"
        name = "æ ‡ç­¾"
        url = "/tags/"
        weight = 30

    [[menu.main]]
        identifier = "search"
        name = "æœç´¢"
        url = "/search/"
        weight = 40