baseURL = 'https://fanhhh.top/'
languageCode = 'zh-cn'
title = "Fanhhh's blog"
theme = 'PaperMod'

sectionPagesMenu = "main"

[outputs]
    home = ["HTML", "RSS", "JSON"]

[params]
    description = "Fanhhhçš„æŠ€æœ¯ä¸ç”Ÿæ´»è®°å½•"
    # æ ¸å¿ƒè®¾ç½®ï¼šauto è¡¨ç¤ºè·Ÿéšç³»ç»Ÿï¼Œlight ä¸ºæµ…è‰²ï¼Œdark ä¸ºæ·±è‰²
    defaultTheme = "auto"
    showCodeCopyButtons = true
    comments = true
    
    # --- æ–‡ç« å…ƒæ•°æ® ---
    showPostMeta = true
    showReadingTime = true
    showWordCount = true

    # --- æ‰©å±•å‚æ•° (éœ€é…åˆä½ çš„ä»£ç ä¿®æ”¹ç”Ÿæ•ˆ) ---
    [params.busuanzi]
        enable = true

    [params.twikoo]
        enable = true
        envId = 'https://comment.fanhhh.top' 

    [params.homeInfoParams]
        Title = "WelcomeğŸ‘‹"
        Content = "è¿™é‡Œæä¾›ä¸€äº›å…³äºæŠ€æœ¯çš„è¯é¢˜ï¼Œå´‡å°šè‡ªç”±ï¼Œæ¬¢è¿å¤§å®¶è‡ªç”±ç•™è¨€"

    [[params.socialIcons]]
        name = "github"
        url = "https://github.com/Fax-han"

# --- èœå•è®¾ç½® ---
[menu]
    [[menu.main]]
        identifier = "archives"
        name = "æ–‡ç« åˆ—è¡¨"
        url = "/archives"
        weight = 20
    
    [[menu.main]]
        identifier = "tags"
        name = "æ ‡ç­¾"
        url = "/tags"
        weight = 30

    [[menu.main]]
        identifier = "search"
        name = "æœç´¢"
        url = "/search"
        weight = 40